# Applied Data Science Capstone Assignment 2 :Segmenting and Clustering Neighborhoods in Toronto - Part 1

For this assignment, you will be required to explore and cluster the neighborhoods in Toronto.

In [29]:
#Import Necessary Libraries

import requests
import lxml.html as lh
import pandas as pd

# Scrap Table Cells

In [30]:
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

#Create a handle, page, to handle the contents of the website
page = requests.get(url)

#Store the contents of the website under doc
doc = lh.fromstring(page.content)

#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [31]:
#Check the length of the first 12 rows
[len(T) for T in tr_elements[:12]]

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [32]:
# Parse the first row as our header
tr_elements = doc.xpath('//tr')

#Create empty list
col=[]
i=0

#For each row, store each first element (header) and an empty list
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print ('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Postal Code
"
2:"Borough
"
3:"Neighborhood
"

# Create Pandas Dataframe

In [33]:
#Since out first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 3, the //tr data is not from our table 
    if len(T)!=3:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [34]:
# Check the length of each column. Ideally, they should all be the same
[len(C) for (title,C) in col]

[181, 181, 181]

In [35]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [36]:
# Access the top 5 rows of the data frame 
df.head()

  Postal Code\n           Borough\n               Neighborhood\n
0         M1A\n      Not assigned\n                           \n
1         M2A\n      Not assigned\n                           \n
2         M3A\n        North York\n                  Parkwoods\n
3         M4A\n        North York\n           Victoria Village\n
4         M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [37]:
# Rename Columns
df.columns = ['PostalCode', 'Borough','Neighborhood']
cols = df.columns.tolist()
df = df[cols]
df.head()

  PostalCode             Borough                 Neighborhood
0      M1A\n      Not assigned\n                           \n
1      M2A\n      Not assigned\n                           \n
2      M3A\n        North York\n                  Parkwoods\n
3      M4A\n        North York\n           Victoria Village\n
4      M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [38]:
# Remove the "/n"
df = df.replace('\n',' ', regex=True)
df.head()

  PostalCode            Borough                Neighborhood
0       M1A       Not assigned
1       M2A       Not assigned
2       M3A         North York                   Parkwoods
3       M4A         North York            Victoria Village
4       M5A   Downtown Toronto   Regent Park, Harbourfront

In [39]:
df = df[df.Borough != 'Not assigned']
df.head(10)

  PostalCode            Borough                                  Neighborhood
0       M1A       Not assigned
1       M2A       Not assigned
2       M3A         North York                                     Parkwoods
3       M4A         North York                              Victoria Village
4       M5A   Downtown Toronto                     Regent Park, Harbourfront
5       M6A         North York              Lawrence Manor, Lawrence Heights
6       M7A   Downtown Toronto   Queen's Park, Ontario Provincial Government
7       M8A       Not assigned
8       M9A          Etobicoke       Islington Avenue, Humber Valley Village
9       M1B        Scarborough                                Malvern, Rouge

In [22]:
df.head()

  PostalCode            Borough                Neighborhood
0       M1A       Not assigned
1       M2A       Not assigned
2       M3A         North York                   Parkwoods
3       M4A         North York            Victoria Village
4       M5A   Downtown Toronto   Regent Park, Harbourfront